//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopFull.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminPanel
    {
        public int Id { get; set; }
        public string AdminName { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
    }
}
